name: sutineki
version: 1.0
main: org.cengiz1.sutineki.SutInekAlmaPlugin
api-version: 1.19
author: DSNG
commands:
  sütinekial:
    permission: op
    description: Süt inek çağırmak için komut
    usage: /sütinekial
  sütinekyemekal:
    permission: op
    description: Süt inek yemeği almasını sağlar
    usage: /inekyemekal